export default {
  signin: "Sign In",
  signup: "Sign Up",
  firstname: "First name",
  lastname: "Last name",
  username: "Username",
  email: "Email",
  password: "Password",
  register: "Sign up",
  signout: "Sign out",
  cancel: "Cancel",
  submit: "Submit",
  changeimage: "Change Image",
  changepassword: "Change password",
  userprofileedit: "User profile edit",
  quicksearch: "Quick search",
  searchmovies: "Search movies",
  sortby: "Sort by",
  name: "Name",
  rating: "Rating",
  released: "Released",
  trending: "Trending",
  updated: "Updated",
  year: "Year",
  order: "Order",
  ascending: "Ascending",
  descending: "Descending",
  all: "All",
  comedy: "Comedy",
  action: "Action",
  horror: "Horror",
  scifi: "Sci-fi",
  romance: "Romance",
  thriller: "Thriller",
  drama: "Drama",
  adventure: "Adventure",
  animation: "Animation",
  documentary: "Documentary",
  crime: "Crime",
  all: "All",
  yeargap: "Year gap",
  ratinggap: "Rating gap",
  advancedsearch: "Advanced search",
  enteryourfirstname: "Enter your first name",
  enteryourlastname: "Enter your last name",
  enterausername: "Enter a username",
  enteryouremail: "Enter your email",
  enterapassword: "Enter a password",
  forgotpassword: "Forgot password ?",
};
