export default {
  signin: "Sign In",
  signup: "Sign Up",
  firstname: "First name",
  lastname: "Last name",
  username: "Username",
  email: "Email",
  password: "Password",
  register: "Resgister",
  signout: "Sign out",
  cancel: "Cancel",
  submit: "Submit",
  changeimage: "Change Image",
  changepassword: "Change password",
  userprofileedit: "User profile edit",
};
