export default {
  signin: "Connexion",
  signup: "Inscription",
  firstname: "Prénom",
  lastname: "Nom",
  username: "Nom d'utilisateur",
  email: "Email",
  password: "Mot de passe",
  register: "S'enregistrer",
  signout: "Se déconnecter",
  cancel: "Annuler",
  submit: "Envoyer",
  changeimage: "Changer l'image",
  changepassword: "Changer le mot de passe",
  userprofileedit: "Editer le profile",
};
