export default {
  signin: "Connexion",
  signup: "Inscription",
  firstname: "Prénom",
  lastname: "Nom",
  username: "Nom d'utilisateur",
  email: "Email",
  password: "Mot de passe",
  register: "S'enregistrer",
  signout: "Se déconnecter",
  cancel: "Annuler",
  submit: "Envoyer",
  changeimage: "Changer l'image",
  changepassword: "Changer le mot de passe",
  userprofileedit: "Editer le profile",
  quicksearch: "Recherche rapide",
  searchmovies: "Chercher film",
  sortby: "Trier par",
  name: "Titre",
  rating: "Evalutaion",
  released: "Date de sortie",
  trending: "Tendance",
  updated: "Updated",
  year: "Année",
  order: "Ordre",
  ascending: "Ascendant",
  descending: "Descendant",
  all: "Tous",
  comedy: "Comedie",
  action: "Action",
  horror: "Horreur",
  scifi: "Sci-fi",
  romance: "Romantique",
  thriller: "Thriller",
  drama: "Drama",
  adventure: "Aventure",
  animation: "Animation",
  documentary: "Documentaire",
  crime: "Crime",
  yeargap: "Intervale d'année",
  ratinggap: "Intervale de note",
  advancedsearch: "Recherche avancée",
  enteryourfirstname: "Entrer votre prénom",
  enteryourlastname: "Entrer votre nom",
  enterausername: "Entrer un nom d'utilisateur",
  enteryouremail: "Entrer un email",
  enterapassword: "Entrer un mot de passe",
};
